name: CI
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  schedule:
    - cron:  '0 4 * * *'
jobs:
  Test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
      - name: Run tests
        run: mvn -s -B -DtestLogLevel=OFF test
